# This file contains the parameters for the Kedro project

# AutoGluon parameters
ag_label: price
ag_excluded_features: [ "id", "ID" ]

# Azure Upload parameters
model_path: data/06_models/autogluon/predictor.pkl
